version: "3"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis
      - APP_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - ./:/app
      - /app/node_modules

  redis:
    image: redis
    ports:
      - "6379:6379"